version: '3.7'

services:
    backend:
        build:
            context: ../
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        expose:
            - "8080"

    frontend:
        build:
            context: ../storeclient
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        restart: always
        depends_on:
            - backend
        links:
            - backend
